
~dirt.loadSoundFiles("/run/media/will/C052-0E64/Music/MO3/MO3_sf2_wavs");
~dirt.loadSoundFiles("/run/media/will/C052-0E64/Music/mine/Mrandom");


~dirt.loadSoundFiles("/run/media/will/C052-0E64/Music/smb_step_and_roll/bgm_w5_s3");
~dirt.loadSoundFiles("/run/media/will/C052-0E64/Music/smb_step_and_roll/bgm_marathon");
~dirt.loadSoundFiles("/run/media/will/C052-0E64/Music/smb_step_and_roll/bgm_events");
~dirt.loadSoundFiles("/run/media/will/C052-0E64/Music/shawn_kemp");
~dirt.loadSoundFiles("/run/media/will/C052-0E64/Music/halflife/*");
~dirt.loadSoundFiles("/run/media/will/C052-0E64/Music/yume_nikki");

~dirt.loadSoundFiles("/run/media/will/C052-0E64/Music/games/halflife/*");


~dirt.loadSoundFiles("/run/media/will/C052-0E64/Music/palmolive")
~dirt.loadSoundFiles("/M/tidalSamples/customSamples/longdoom")
~dirt.loadSoundFiles("/run/media/will/C052-0E64/Music/serious_shit")
~dirt.loadSoundFiles("/run/media/will/C052-0E64/Music/aint_it_funny")





~dirt.loadSoundFiles("/home/will/C052-0E64/Music/ai_breaks/ai_example_breaks")